site_name: Centurion Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.path
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: es
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
plugins:
    - search
    - mermaid2

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/amatosolivo
    - icon: fontawesome/brands/twitter
      link: https://x.com/alex_sotam
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alexander-matos-olivo-71870529/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/amatosolivo"  target="_blank" rel="noopener">Alexander Matos</a>

nav:
- Inicio: index.md
- Analisis: analisis.md
- Arquitectura:
  - Descripción General: arquitectura/descripcion-general.md
  - Modelos de Datos: arquitectura/modelos-datos.md
  - Recursos: arquitectura/recursos.md
  - Componentes del Sistema: arquitectura/componentes.md
- Soporte y FAQ:
  - Preguntas Frecuentes: soporte/faq.md
  - Resolución de Problemas: soporte/resolucion-problemas.md
- Contribución: contribucion.md
- Historial de Cambios: changelog.md